name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Dotnet 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.200'

    - name: Set Run Permissions for Scripts
      run: sudo chmod +x ./infra/scripts/*

    - name: Build and Test Application
      run: .src/infra/scripts/build.sh

    - name: Run Application
      run: .src/infra/scripts/run.sh ${{ secrets.GITHUBUSERNAME }} ${{ secrets.GITHUBPASSWORD }}